/*
 * Jerry Zhang
 * Mr. Eng
 * AT Java
 * HW09 PartC
 */

import java.util.Random;

public class PartC {
    public static void main(String[] args) {
        Random random = new Random();
        int total = 0;
        int i = 1;
        for (i = 1; i <= 1000; i++) {
            int number = random.nextInt(1, 11);
            total = total + number;
        }
        System.out.println("The average is " + (double) total / i);
    }
}
// the average calculated makes sense. From random numbers between
// 1-10(inclusive), the average should theoretically be 5.5. When run multiple
// times, the average of the psuedo random numbers generated by the program is
// around 5.5
